version: '3'

services:
  app:
    build:
      context: ./
    ports:
     - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - bundle:/bundle
      - node_modules:/usr/src/app/node_modules
    tmpfs:
      - /usr/src/app/tmp
    working_dir:
      /usr/src/app
    command: >
      bash -c 'bundle config set --local path "/bundle" && bundle install && ./bin/rails s -b "0.0.0.0"'

volumes:
  bundle:
  node_modules:
