version: '3'

services:
  app:
    build:
      context: ./
    ports:
     - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - bundle:/bundle
      - node_modules:/usr/src/app/node_modules
    tmpfs:
      - /usr/src/app/tmp
    working_dir:
      /usr/src/app
    entrypoint: ["/opt/bin/entrypoint.sh"]
    command: >
      bash -c 'bundle config set --local path "/bundle" && tail -f /dev/null'
    environment:
      HOST_USER: $USER
      HOST_UID: $UID
      HOST_GID: $GID

volumes:
  bundle:
  node_modules:
